AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/bundle/**/*'

Layout/ArgumentAlignment:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true
