name: CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - dev-main
      - main
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - env:
          RAILS_ENV: test
        run: bin/rails db:setup
      - env:
          RAILS_ENV: test
        run: bin/rails spec
